import { LangDef } from "../types"
import { jeRule, jRules, sRule, xRules } from "./_shared"

export const be: LangDef[] = [
  {
    from: "be",
    to: "de",
    dict: {
      а: "a",
      б: "b",
      в: "w",
      г: "h",
      д: "d",
      е: "e",
      ё: "jo",
      ж: "sh",
      з: "s",
      і: "i",
      й: "i",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ў: "u",
      ф: "f",
      х: "ch",
      ц: "z",
      ч: "tsch",
      ш: "sch",
      ы: "y",
      ь: "",
      э: "e",
      ю: "ju",
      я: "ja",
    },
    rules: [
      jeRule,
      ...xRules,
      sRule,
      ...jRules,
      {
        desc: "й nicht wiedergegeben nach ы und і",
        cond: ({ c, prev }) => c === "й" && ["ы", "і"].includes(prev),
        val: "",
        range: [-1, 1],
      },
      {
        desc: "V statt W am Wortbeginn (gebräuchliche Namensschreibung)",
        cond: ({ c, w }) =>
          c === "в" && !!w.match(/^(валянцін|віктар|веранік)/i),
        val: "v",
      },
    ],
  },
  {
    from: "be",
    to: "en",
    dict: {
      а: "a",
      б: "b",
      в: "v",
      г: "h",
      д: "d",
      е: "e",
      ё: "yo",
      ж: "zh",
      з: "z",
      і: "i",
      й: "i",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ў: "u",
      ф: "f",
      х: "kh",
      ц: "ts",
      ч: "ch",
      ш: "sh",
      ы: "y",
      ь: "",
      э: "e",
      ю: "yu",
      я: "ya",
    },
  },
  {
    from: "be",
    to: "scientific",
    dict: {
      а: "a",
      б: "b",
      в: "v",
      г: "h",
      д: "d",
      е: "e",
      ё: "ё",
      ж: "ž",
      з: "z",
      і: "i",
      й: "j",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ў: "ŭ",
      ф: "f",
      х: "ch",
      ц: "c",
      ч: "č",
      ш: "š",
      ы: "y",
      ь: "ʹ",
      э: "ė",
      ю: "ju",
      я: "ja",
      "'": "’",
      "’": "’",
      ʼ: "’",
    },
  },
]
