import { LangDef } from "../types"
import { jeRule, jRules, sRule, xRules } from "./_shared"

export const ru: LangDef[] = [
  {
    from: "ru",
    to: "de",
    dict: {
      а: "a",
      б: "b",
      в: "w",
      г: "g",
      д: "d",
      е: "e",
      ё: "jo",
      ж: "sh",
      з: "s",
      и: "i",
      й: "i",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ф: "f",
      х: "ch",
      ц: "z",
      ч: "tsch",
      ш: "sch",
      щ: "schtsch",
      ъ: "",
      ы: "y",
      ь: "",
      э: "e",
      ю: "ju",
      я: "ja",
    },
    rules: [
      jeRule,
      ...xRules,
      sRule,
      ...jRules,
      {
        desc: "й nicht wiedergegeben nach ы und и",
        cond: ({ c, prev }) => c === "й" && ["ы", "и"].includes(prev),
        val: "",
        range: [-1, 1],
      },
      {
        desc: "ё -> o nach ж / ч / ш / щ",
        cond: ({ c, prev }) => c === "ё" && ["ж", "ч", "ш", "щ"].includes(prev),
        val: "o",
        range: [-1, 1],
      },
      {
        desc: "-ого/-его -> -owo/-ewo am Wortende",
        cond: ({ c, prev, next, charAtPos }) =>
          c === "г" &&
          ["е", "о"].includes(prev) &&
          next === "о" &&
          charAtPos(+2) === "",
        val: "w",
        range: [-1, 2],
      },
      {
        desc: "Александр -> Alexander (gebräuchliche Namensschreibung)",
        cond: ({ c, w }) => c === "д" && w === "александр",
        val: "de",
        range: [0, 2],
      },
      {
        desc: "Дмитрий -> Dimitri (gebräuchliche Namensschreibung)",
        cond: ({ c, w }) => c === "д" && w === "дмитрий",
        val: "di",
        range: [0, 2],
      },
      {
        desc: "j statt i am Wortende (gebräuchliche Namensschreibung)",
        cond: ({ c, w }) => c === "й" && ["алексей", "сергей"].includes(w),
        val: "j",
      },
      {
        desc: "V statt W am Wortbeginn (gebräuchliche Namensschreibung)",
        cond: ({ c, w }) =>
          c === "в" && !!w.match(/^(валентин|виктор|вероник)/i),
        val: "v",
      },
    ],
  },
  {
    from: "ru",
    to: "en",
    dict: {
      а: "a",
      б: "b",
      в: "v",
      г: "g",
      д: "d",
      е: "e",
      ё: "yo",
      ж: "zh",
      з: "z",
      и: "i",
      й: "i",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ф: "f",
      х: "kh",
      ц: "ts",
      ч: "ch",
      ш: "sh",
      щ: "sch",
      ъ: "",
      ы: "y",
      ь: "",
      э: "e",
      ю: "yu",
      я: "ya",
    },
  },
  {
    from: "ru",
    to: "scientific",
    dict: {
      а: "a",
      б: "b",
      в: "v",
      г: "g",
      д: "d",
      е: "e",
      ё: "ё",
      ж: "ž",
      з: "z",
      и: "i",
      й: "j",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ф: "f",
      х: "ch",
      ц: "c",
      ч: "č",
      ш: "š",
      щ: "šč",
      ъ: "ʺ",
      ы: "y",
      ь: "ʹ",
      э: "ė",
      ю: "ju",
      я: "ja",
      "'": "’",
      "’": "’",
      ʼ: "’",
    },
  },
]
