import { LangDef } from "../types"
import { jRules, sRule, xRules } from "./_shared"

export const uk: LangDef[] = [
  {
    from: "uk",
    to: "de",
    dict: {
      а: "a",
      б: "b",
      в: "w",
      г: "h",
      ґ: "g",
      д: "d",
      е: "e",
      є: "e",
      ж: "sh",
      з: "s",
      и: "y",
      і: "i",
      ї: "ji",
      й: "i",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ф: "f",
      х: "ch",
      ц: "z",
      ч: "tsch",
      ш: "sch",
      щ: "schtsch",
      ь: "",
      ю: "ju",
      я: "ja",
      "'": "",
      "’": "",
      ʼ: "",
    },
    rules: [
      {
        desc: "є -> je am Wortanfang, nach ь und Vokalen",
        cond: ({ c, prev, isVowel }) =>
          c === "є" && (isVowel(prev) || ["", "ь"].includes(prev)),
        val: "je",
        range: [-1, 1],
      },
      ...xRules,
      sRule,
      {
        desc: "й nicht wiedergegeben nach и",
        cond: ({ c, prev }) => c === "й" && prev === "и",
        val: "",
        range: [-1, 1],
      },
      ...jRules,
      {
        desc: "V statt W am Wortbeginn (gebräuchliche Namensschreibung)",
        cond: ({ c, w }) =>
          c === "в" && !!w.match(/^(валентин|віктор|веронік)/i),
        val: "v",
      },
    ],
  },

  {
    from: "uk",
    to: "en",
    dict: {
      а: "a",
      б: "b",
      в: "v",
      г: "h",
      ґ: "g",
      д: "d",
      е: "e",
      є: "ie",
      ж: "zh",
      з: "z",
      и: "y",
      і: "i",
      ї: "i",
      й: "i",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ф: "f",
      х: "kh",
      ц: "ts",
      ч: "ch",
      ш: "sh",
      щ: "shch",
      ь: "",
      ю: "iu",
      я: "ia",
      "'": "",
      "’": "",
      ʼ: "",
    },
    rules: [
      {
        desc: "є -> ye at the beginning of the word",
        cond: ({ c, prev }) => c === "є" && prev === "",
        val: "ye",
      },
      {
        desc: "ї -> yi at the beginning of the word",
        cond: ({ c, prev }) => c === "ї" && prev === "",
        val: "yi",
      },
      {
        desc: "й -> y at the beginning of the word",
        cond: ({ c, prev }) => c === "й" && prev === "",
        val: "y",
      },
      {
        desc: "ю -> yu at the beginning of the word",
        cond: ({ c, prev }) => c === "ю" && prev === "",
        val: "yu",
      },
      {
        desc: "я -> ya at the beginning of the word",
        cond: ({ c, prev }) => c === "я" && prev === "",
        val: "ya",
      },
      {
        desc: "зг -> zgh",
        cond: ({ c, prev }) => c === "г" && prev === "з",
        val: "gh",
        range: [-1, 1],
      },
    ],
  },
  {
    from: "uk",
    to: "scientific",
    dict: {
      а: "a",
      б: "b",
      в: "v",
      г: "h",
      ґ: "g",
      д: "d",
      е: "e",
      є: "je",
      ж: "ž",
      з: "z",
      и: "y",
      і: "i",
      ї: "ji",
      й: "j",
      к: "k",
      л: "l",
      м: "m",
      н: "n",
      о: "o",
      п: "p",
      р: "r",
      с: "s",
      т: "t",
      у: "u",
      ф: "f",
      х: "ch",
      ц: "c",
      ч: "č",
      ш: "š",
      щ: "šč",
      ь: "ʹ",
      ю: "ju",
      я: "ja",
      "'": "’",
      "’": "’",
      ʼ: "’",
    },
  },
]
